// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7VJcAoAtkuUobWTN92Yfjyyrmbj7KwU8',
    appId: '1:674104501565:web:e419bbb97a16525f9ad154',
    messagingSenderId: '674104501565',
    projectId: 'rcts-pwa-2027',
    authDomain: 'rcts-pwa-2027.firebaseapp.com',
    storageBucket: 'rcts-pwa-2027.firebasestorage.app',
    measurementId: 'G-GM5BR9S253',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4DHOcXGshlxEN228iXsykIjLq8NE6ZXI',
    appId: '1:674104501565:android:e65f587f91d760189ad154',
    messagingSenderId: '674104501565',
    projectId: 'rcts-pwa-2027',
    storageBucket: 'rcts-pwa-2027.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzNRN359HGUpbRyZTD-hxdL49Zp1qJKLo',
    appId: '1:674104501565:ios:ddb61eb371a60e489ad154',
    messagingSenderId: '674104501565',
    projectId: 'rcts-pwa-2027',
    storageBucket: 'rcts-pwa-2027.firebasestorage.app',
    iosBundleId: 'com.rcts.myNewApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzNRN359HGUpbRyZTD-hxdL49Zp1qJKLo',
    appId: '1:674104501565:ios:ddb61eb371a60e489ad154',
    messagingSenderId: '674104501565',
    projectId: 'rcts-pwa-2027',
    storageBucket: 'rcts-pwa-2027.firebasestorage.app',
    iosBundleId: 'com.rcts.myNewApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7VJcAoAtkuUobWTN92Yfjyyrmbj7KwU8',
    appId: '1:674104501565:web:01f1b5dc1d489cea9ad154',
    messagingSenderId: '674104501565',
    projectId: 'rcts-pwa-2027',
    authDomain: 'rcts-pwa-2027.firebaseapp.com',
    storageBucket: 'rcts-pwa-2027.firebasestorage.app',
    measurementId: 'G-PCL8MN5S64',
  );

}